<?php // DIS PROPRIETARY CODE - NO THIRD-PARTY DEPENDENCIES
// © 2026 Digital Intelligence Solutions LLC, Muscat, Oman
// GENERATED BY WINDSURF AI UNDER DIS POLICY
// VERIFY AGAINST: https://github.com/dis-fx/fx-nucleus/FRAMEWORK_PLAN.md

declare(strict_types=1);

use Dis\FictionX\Router\Request;
use Dis\FictionX\Router\Response;
use Dis\FictionX\Router\Router;

require __DIR__ . '/../src/Request.php';
require __DIR__ . '/../src/Response.php';
require __DIR__ . '/../src/Router.php';

final class Test
{
    private int $passed = 0;
    private int $failed = 0;

    public function run(string $name, callable $fn): void
    {
        try {
            $fn();
            $this->passed++;
            echo "[PASS] {$name}\n";
        } catch (Throwable $e) {
            $this->failed++;
            echo "[FAIL] {$name}: {$e->getMessage()}\n";
        }
    }

    public function assertTrue(bool $value, string $message = 'Expected true'): void
    {
        if ($value !== true) {
            throw new RuntimeException($message);
        }
    }

    public function assertSame($expected, $actual, string $message = 'Values are not the same'): void
    {
        if ($expected !== $actual) {
            $exp = var_export($expected, true);
            $act = var_export($actual, true);
            throw new RuntimeException($message . " (expected {$exp}, got {$act})");
        }
    }

    public function summary(): int
    {
        echo "\nPassed: {$this->passed}\nFailed: {$this->failed}\n";
        return $this->failed === 0 ? 0 : 1;
    }
}

$T = new Test();

$T->run('GET route returns 200', function () use ($T) {
    $router = new Router();
    $router->get('/hello', fn(Request $r) => Response::text('ok'));

    $res = $router->dispatch(new Request('GET', '/hello'));

    $T->assertSame(200, $res->status());
    $T->assertSame('ok', $res->body());
});

$T->run('405 includes Allow header', function () use ($T) {
    $router = new Router();
    $router->post('/p', fn(Request $r) => Response::text('posted'));

    $res = $router->dispatch(new Request('GET', '/p'));

    $T->assertSame(405, $res->status());
    $headers = $res->headers();
    $T->assertTrue(isset($headers['Allow']), 'Allow header missing');
    $T->assertTrue(strpos($headers['Allow'], 'POST') !== false, 'Allow does not include POST');
    $T->assertTrue(strpos($headers['Allow'], 'OPTIONS') !== false, 'Allow does not include OPTIONS');
});

$T->run('OPTIONS returns 204 with Allow', function () use ($T) {
    $router = new Router();
    $router->get('/x', fn(Request $r) => Response::text('x'));

    $res = $router->dispatch(new Request('OPTIONS', '/x'));

    $T->assertSame(204, $res->status());
    $headers = $res->headers();
    $T->assertTrue(isset($headers['Allow']), 'Allow header missing');
    $T->assertSame('', $res->body());
});

$T->run('HEAD behaves like GET but empty body', function () use ($T) {
    $router = new Router();
    $router->get('/h', fn(Request $r) => Response::text('body'));

    $res = $router->dispatch(new Request('HEAD', '/h'));

    $T->assertSame(200, $res->status());
    $T->assertSame('', $res->body());
});

exit($T->summary());
